### ISSUE TITLE
不具合

### ISSUE THREAD

**Issue by c0a2106090** [c0b21180/ProjExD#4]
https://github.com/c0b21180/ProjExD/blob/f801985a7e6a98296c7eed1add976919fdf43a3b/ex01/alphabet.py#L37
in seikai から回答したものを抜き取っていかないと同じ回答し続けるだけでゲームクリアになってしまう(違ってたら申し訳ない)。

**Comment by c0a2106090** [comment]
変数他の人のから変えてなかった。申し訳ない。

**Comment by c0b21180** [comment]
その通りでした。
ありがとうございます
